---
title: "Statistics with R"
subtitle: "Modelling Data with R"
author: "Dragonfly Stats"
date: "2016/12/12"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

1 In a small country, a political election was held recently to decide on a political party 
to govern the country. A survey was conducted to monitor the approval rating for the 
winning political party. 
A sample of 15 voters were asked to complete the same survey twice: once before the 
election (Approval before) and a second time 6 months after the election (Approval 
after). The survey asked each of the 15 voters to record their approval for the winning 
political party on a scale from 1 to 10, where 
1 = Strongly disapprove and 10 = Strongly approve. 
The results are shown in the table below:
Voter 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
Approval 
before 8 6 8 7 7 4 2 10 8 7 10 8 8 9 6 
Approval 
after 5 6 2 3 4 1 4 7 4 2 10 1 5 3 7 
The values can be entered in R using: 
```{r}
approval_before <- c(8, 6, 8, 7, 7, 4, 2, 10, 8, 7, 10, 
8, 8, 9, 6) 
approval_after <- c(5, 6, 2, 3, 4, 1, 4, 7, 4, 2, 10, 1, 
5, 3, 7) 

```

---

(i) Calculate the means for the Approval before and Approval after results. [2] 
(ii) Outline why Kendall’s Tau would be a suitable correlation coefficient to use 
for these results. [2] 
(iii) Calculate Kendall’s Tau coefficient between the Approval before and 
Approval after results. 

---

(iv) Comment on your results in parts (i) and (iii). 