Q. 1)
Use the data file “Mortality_Investigation.csv” to answer the below questions. This table
contains the details of mortality investigation performed on 100 different male lives
between 1-Jan-2016 and 31-Dec-2018.
i)
Print first 6 rows of the data ensuring correct data formats for all the columns and
calculate the proportion of the total sample died, survived and withdrew from the
observation period. (4)
ii) Compute two new columns ‘Age_At_Entry’ and ‘Age_At_Exit’ for each person (you
can assume a completed year as 365.25 days and you can compute the age as difference
between the dates in decimals like 35.234 years) and print the last 6 rows of the newly
formed table. (5)
iii) Compute the average age at entry and the average age at exit of the people for whom
“Death” was the reason of Exit. (3)
If the age label used is “Age last Birthday”, then calculate
iv) Number of lives out of total 100 lives who have contributed the full year towards the
c
central exposed to risk E 37
. (4)
c
v) Number of lives who did not contribute at all towards the central exposed to risk E 37
. (4)
c
vi) Total number of years of contribution to E 37
by all the lives together (Round your
answer to 2 digits after the decimal).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Solution 1:
i)
```{r}
Mort_Inv <- read.csv("D: /Mortality_Investigation.csv")
Mort_Inv$DoB<-as.Date(Mort_Inv$DoB)
Mort_Inv$DoJ<-as.Date(Mort_Inv$DoJ)
Mort_Inv$DoE<-as.Date(Mort_Inv$DoE)

```
head(Mort_Inv) [2]
prop.table(table(Mort_Inv$Exit_Reason)) [2]
> head(Mort_Inv)
Life
DoB
DoJ
DoE Exit_Reason
1
A1 1981-12-12 2018-11-13 2018-12-31
Survived
2
A2 1981-05-22 2017-10-06 2018-12-31
Survived
3
A3 1978-08-11 2018-01-30 2018-12-31
Survived
4
A4 1980-05-24 2016-05-12 2016-05-13 Withdrawal
5
A5 1979-04-03 2017-07-25 2018-12-31
Survived
6
A6 1979-11-08 2016-08-02 2017-04-14
Death
> prop.table(table(Mort_Inv$Exit_Reason))
Death
0.31
Survived Withdrawal
0.40
0.29
[4]
ii)
Mort_Inv$Age_At_Entry<-round((Mort_Inv$DoJ-Mort_Inv$DoB)/365.25,4)
Mort_Inv$Age_At_Exit<-round((Mort_Inv$DoE-Mort_Inv$DoB)/365.25,4)
tail(Mort_Inv)
> tail(Mort_Inv)
Life
DoB
95
A95 1981-03-28
96
A96 1981-01-17
97
A97 1980-01-17
98
A98 1978-04-17
99
A99 1978-06-12
100 A100 1980-06-29
DoJ
2016-03-06
2018-04-04
2016-08-29
2016-06-14
2017-09-05
2018-03-27
DoE Exit_Reason Age_At_Entry Age_At_Exit
2019-11-21
Survived 34.9405 days 38.6502 days
2018-09-14
Death 37.2101 days 37.6564 days
2016-09-18
Death 36.6160 days 36.6708 days
2016-07-07 Withdrawal 38.1602 days 38.2231 days
2019-11-25
Survived 39.2334 days 41.4538 days
2019-10-04
Survived 37.7413 days 39.2635 days

iii)
mean(Mort_Inv$Age_At_Entry[Mort_Inv$Exit_Reason == "Death"])
mean(Mort_Inv$Age_At_Exit[Mort_Inv$Exit_Reason == "Death"])
> mean(Mort_Inv$Age_At_Entry[Mort_Inv$Exit_Reason == "Death"])
Time difference of 37.01715 days
> mean(Mort_Inv$Age_At_Exit[Mort_Inv$Exit_Reason == "Death"])
Time difference of 37.89168 days

iv)
sum((Mort_Inv$Age_At_Entry)<37&Mort_Inv$Age_At_Exit>38)
 14
[4]
Page 2 of 11IAI
CS2B-1120
v)
sum((Mort_Inv$Age_At_Entry)>38|Mort_Inv$Age_At_Exit<37)
 49
[4]
vi)
Mort_Inv$Contribution37<-ifelse((Mort_Inv$Age_At_Exit<37 |Mort_Inv$Age_At_Entry> 38),"No","Yes" )
Mort_Inv$contribution37_Period<-ifelse(Mort_Inv$Contribution37 == "Yes",
(pmin(38,Mort_Inv$Age_At_Exit)- pmax(37,Mort_Inv$Age_At_Entry)),0)
sum(Mort_Inv$contribution37_Period)
 27.4224
[7]
[27 Marks]
