---
title: "Statistics with R"
subtitle: "Introduction to R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---


3 Before answering this question, the ‘survival’ package should be loaded into R using 
the following code: 
install.packages("survival") 
library(survival)

---

A recently developed drug, MediCo, has been used over the past 12 months to treat a 
potentially fatal disease. MediCo was approved by a medical regulator last year 
following initial trials and mortality data has been collected over the past 12 months, 
since approval, to continue reviewing the drug’s effectiveness. 
This mortality data has been compared with mortality data collected from infected 
patients, prior to MediCo’s approval, who were NOT administered the drug. 
It is suspected that gender may be a significant covariate on the mortality rate of 
infected patients. 

---

The ‘CS2B_Apr_21_Qu_3_Data.csv’ file contains the combined mortality data from 
this investigation for 4,400 infected patients. The file contains the following five 
variables: 

* Life Unique patient identifier (integers 1, 2, …, 4,400) 
* Drug Drug indicator (1 = received drug, 0 = did not receive drug) 
* Gender Gender indicator (1 = female, 0 = male) 
* Status Status indicator (1 = death due to disease, 0 = censoring event 
occurred) 
* 9Time Duration in days at which death/censoring occurred (integers with a 
range of 1–365, with 1 = first day of the investigation and 
365 = last day of the investigation). 
Before answering this question, the ‘CS2B_Apr_21_Qu_3_Data.csv’ file should be 
loaded into R and assigned to a data frame called mortalitydata. 


---

## Part 1

(i) Plot the Kaplan–Meier survival function estimate for all patients, together with 
its two-sided 99.5% confidence interval. 



---

### Part 2

(ii) Determine, using the estimated survival function from part (i), the probability 
that a patient survived from the beginning of the investigation to the end of the 
investigation.

---

### Part 3

(iii) Evaluate the appropriateness of the probability value, calculated in part (ii), 
for assessing MediCo’s effectiveness. 

---

### Part 4

(iv) Plot, on a single graph, four Kaplan–Meier survival function estimates without 
any confidence intervals, where each estimate represents one of the four 
possible patient group combinations of drug and gender. You should use 
separate colours to identify each survival function. 


---

### Part 5

(v) Comment on the graph produced in part (iv).  

