---
title: "Statistics with R"
subtitle: "Statistical Modelling with R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(knitr)


```

```{css, echo=FALSE}
pre {
  background: #ADD8E6;
  max-width: 100%;
  overflow-x: scroll;
}
```

***CS2B – Risk Modelling and Survival Analysis ***


* The emphasis is placed on being able to apply statistical methods to actuarial problems using real data sets and the open-source software environment R. 

* Time Series. Probability Distributions, Survival Analysis

---

Q3
(i)
mortalitydata =
read.csv(file = "CS2B_Apr_21_Qu_3_Data.csv", head = TRUE)
KMfit = 
survfit( 
 

Surv(mortalitydata$Time, mortalitydata$Status) ~ 1, 
 

conf.int = 0.995) 
 

plot( 
 

KMfit, 
 

xlab = "Time", 
 

ylab = "Survival Function, S(t)", 
 

main = "Kaplan-Meier Estimate, with its two-sided 99.5% 
confidence interval, for all patients") 
 


 

(ii)
summary(KMfit, time = 365)$surv
OR:
KMfit$surv[365]
OR:
min(KMfit$surv) 
 


 
 0.1715504 
 



The probability that a patient survived from the beginning of the investigation to the end of 
the investigation is 0.172 
 

(iii)
The probability value calculated in part (ii) is NOT suitable for assessing the effectiveness of 
MediCo 
 

as it is the average lifetime distribution of ALL patients in the investigation, whether they
received MediCo or not 
 

To review the effectiveness of MediCo we need to compare the lifetime distribution of 
patients that received the drug with the lifetime distribution of patients who did not 
 

(iv)
KMfit = 
survfit( 
 

Surv(mortalitydata$Time,mortalitydata$Status)
~Drug+Gender, [2½]
data = mortalitydata) 
 

print(KMfit)
Call: survfit(formula = Surv(mortalitydata$Time, 
mortalitydata$Status) ~ 
 Drug + Gender, data = mortalitydata)
N events median 0.95LCL 0.95UCL
Drug=0, Gender=0 1100 982 70 64 76
Drug=0, Gender=1 1100 870 145 135 158
Drug=1, Gender=0 1100 982 76 70 81
Drug=1, Gender=1 1100 607 295 273 317
OR:
KMfit = 
survfit( 
 

Surv(mortalitydata$Time,mortalitydata$Status)~ 
mortalitydata$Drug + mortalitydata$Gender) [3½]
print(KMfit)
Call: survfit(formula = Surv(mortalitydata$Time, 
mortalitydata$Status) ~ 
 mortalitydata$Drug + mortalitydata$Gender)
n events median
mortalitydata$Drug=0, mortalitydata$Gender=0 1100 982 70
mortalitydata$Drug=0, mortalitydata$Gender=1 1100 870 145
mortalitydata$Drug=1, mortalitydata$Gender=0 1100 982 76
mortalitydata$Drug=1, mortalitydata$Gender=1 1100 607 295
0.95LCL 0.95UCL
mortalitydata$Drug=0, mortalitydata$Gender=0 64 76
mortalitydata$Drug=0, mortalitydata$Gender=1 135 158
mortalitydata$Drug=1, mortalitydata$Gender=0 70 81


mortalitydata$Drug=1, mortalitydata$Gender=1 273 317
-----
plot( 
 

KMfit, 
 

xlab = "Time", 
 

ylab = "Survival Function, S(t)", 
 

main = "Kaplan-Meier Estimate for the four possible patient 
groups", 
 

col = c("blue", "red", "black", "green"), 
 

legend("topright", 
legend = c("Male - No Drug", "Female - No Drug", "Male -
Drug", "Female - Drug"), 
 

col = c("blue", "red", "black", "green"), 
 

pch = 7)

 

(v)
Female patients have a higher overall survival rate than male patients (with or without 
MediCo). 
 

MediCo seems to increase survival rates … 
 

… with the impact being much more significant on female lives than male lives. 
 

EITHER:
The impact of MediCo on male lives may not be statistically significant.


OR:
The impact of MediCo on male lives should be tested for statistical significance. 
 

The survival curves for males actually cross over a few times at later times, i.e. at certain 
points the raw estimates suggest the survival probabilities are higher for males not taking the 
drugs. However, this may be more reflective of a non-significant difference rather than 
MediCo actually reducing survival probabilities at these durations. 
 

[Marks available 5, maximum 3]


[Paper Total 100]
END OF EXAMINERS’ REPORT
Part (i) was well answered, although some candidates showed 95% confidence 
intervals (the default) rather than 99.5% as specified in the question. Candidates are 
reminded to read the question carefully.
Part (ii) was well answered, although some candidates lost marks for not including 
their R output or for not stating their answer separately from the output.
Part (iii) was very poorly answered with most candidates not answering the question 
that was asked. The question asked candidates to evaluate the appropriateness of the 
probability value calculated in part (ii). The question was looking for an explanation 
that the probability value was not appropriate for assessing MediCo’s effectiveness 
and that further information was required.
Answers to part (iv) were generally satisfactory. However, instead of plotting a single 
survfit object, many candidates plotted separate survfit objects, on the same axes, for 
each of the four patient groups. These candidates tended to lose marks for one or 
more of the following reasons:
• Defining the patient groups incorrectly, e.g. conditioning on the Gender and 
Drug fields separately rather than together.
• Producing curves that terminated too early, as not all four patient groups had 
death or censoring events on the last day of the investigation.
• Including confidence intervals, which are excluded by default when a survfit 
object containing multiple survival curves is plotted.
Part (v) was very poorly answered although most candidates who produced the correct 
chart in part (iv) answered part (v) well.
Part (vi) was well answered although many candidates failed to specify the Breslow 
method for tie handling. This must be specified explicitly since the default method is 
the Efron method.
Part (vii) was very poorly answered. Few candidates quantified the impact of MediCo 
or gender on mortality rates. Very few candidates commented on the apparent need 
for an interaction term, which is a key conclusion from this analysis.
Part (viii) was well answered although many candidates used Drug + Gender + Drug 
* Gender in place of Drug * Gender, which was unnecessary because R automatically 
includes the first-order terms.
Part (ix) was very poorly answered. Many candidates commented on the statistical 
significance of gender in isolation, which was not relevant to this part of the question. 
Few candidates commented on the significance of the reduction in mortality from 
taking MediCo for each gender separately, or of the interaction term.
