---
title: "Statistics with R"
subtitle: "Introduction to R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

2 Before answering this question, construct the function, rpareto, in R using the 
following code: 
rpareto = function(n, alpha, lambda){ 
rp = lambda * ((1 - runif(n))^(-1/alpha) - 1) 
rp}
The rpareto function generates a random sample of size n from a two-parameter 
Pareto distribution with parameters α and λ. 

---

### Part 1

(i) Generate, using rpareto, a random sample of size 25,000 from the 
two-parameter Pareto distribution with parameters α = 3 and λ = 1, assigning 
the simulated values to a vector called A_vec. You should set a random 
number generator seed of 123 before generating A_vec and use the R function, 
head(), to display the first eight values of A_vec in your answer script. [3] 

--------------------------
Q2
rpareto = function(n, alpha, lambda){
rp = lambda * ((1 - runif(n))^(-1/alpha) - 1)
rp} 
(i)
set.seed (123) 
 

A_vec = 
 

rpareto(n = 25000, alpha = 3, lambda = 1) 
 

head(A_vec, 8) 
 


 
 0.11966335 0.67788900 0.19160373 1.04468423 1.56103061 
0.01566369 0.28445342 1.10259132 


---

### Part 2

(ii) Construct an R function, called A_exceed_u, with two arguments, A and u, that 
returns only the non-zero entries of a vector, E, where vector E is of length 
25,000, with entries defined as: 
Ei = maxሼAi – u, 0ሽ.
Use the R function, head(), to display in your answer script the first eight 
values of A_exceed_u when A = A_vec and u = 1. 

----------------------------



(ii)
A_exceed_u = 
 

function(A, u){ 
 

E = pmax(A - u, 0) [2½]
output = E[E!=0] 
 

output} 
 

head(A_exceed_u(A = A_vec, u = 1), 8) 
 


 
 0.04468423 0.56103061 0.10259132 0.85069357 0.15317919 
0.80118083 0.08415856 3.58825415 
 
---

### Part 3

(iii) Construct another R function, called F_u, with one argument, 
A_greater_than_u, that returns a vector of length 101, containing the 
probabilities: 
PሺAi – u ≤ x | Ai > u), where x ≥ 0, 
for values of x from 0 to 10 inclusive, at intervals of 0.1. 
Use the R function, head(), to display in your answer script the first eight 
values of F_u when A_greater_than_u = A_exceed_u with arguments 
A = A_vec and u = 1. 
---------------------------------------



(iii)
F_u = 
 

function(A_greater_than_u) { 
 

y = vector(length = 101) 
 

for (i in 1:101) { 
 

y[i] = 
length(A_greater_than_u[A_greater_than_u <= 0.1 * (i-1)]) / 
length(A_greater_than_u) [4]
 }
y} 
 

head(F_u(A_exceed_u(A = A_vec, u = 1)), 8) 
 


 
 0.0000000 0.1463087 0.2526846 0.3439597 0.4201342 
0.4838926 0.5362416 0.5895973 
 


---

### Part 4


(iv) Plot, on a single graph, four line graphs of the values of F_u against x for 
the values of x specified in part (iii) when A_greater_than_u = A_exceed_u, 
A = A_vec and u = 1, 2, 3 and 4. You should use separate colours to identify 
each line graph and you should clearly specify which value of u is represented 
by each of the four line graphs. [10] 
(v) Comment on the graph produced in part (iv). [6] 

---

### Part 5

 
(iv)
x = seq(from = 0, to = 10, by = 0.1) 
 

plot( 
 

x, 
 

F_u(A_greater_than_u = A_exceed_u(A = A_vec,
u = 1)), 
 

type = "l", 
 

main = "Values of F_u against x for u = 1, 2, 3 
and 4", 
 

col = "red", 
 

ylab = "F_u") 
 

lines(x, F_u(A_greater_than_u = A_exceed_u(A = 
A_vec, u = 2), col = "yellow") 
 

lines(x, F_u(A_greater_than_u = A_exceed_u(A = 
A_vec, u = 3), col = "blue") 
 

lines(x, F_u(A_greater_than_u = A_exceed_u(A = 
A_vec, u = 4), col = "green") 
 

legend("bottomright", 
 legend = c("u = 1", "u = 2", "u = 3", 
 "u = 4"), 
 

 col = c("red", "yellow", "blue", "green"), 
 

 pch = 7)

 
---

### Part 5


(v)
For all but the smallest values of x, F_u(x) decreases as u increases. 
 

This is consistent with the result that if X ~ Pa(alpha, lambda), then the threshold exceedance 
X – u | X > u is distributed as Pa(alpha, lambda + u). 
 

There is some irregularity caused by sampling variation due to low data volumes above the 
higher values of u. 
 

As a result of this irregularity, the curves for u = 3 and u = 4 cross over for small values of x.

--- 

[Total 36]
Part (i) was very well answered. The most common errors were to fail to set the 
random number generator seed to 123 and to output the default 6 rather than 8 values 
using the head function.
Part (ii) was well answered. The most common error was to output all the entries of 
the vector E, rather than only the non-zero entries as specified in the question. 
Candidates are reminded to read the question carefully. Candidates unfamiliar with 
the pmax function included more extensive R code than necessary, referring to 
individual vector components.
Part (iii) was poorly answered. Few candidates coded the R function entirely 
accurately. 
Part (iv) was surprisingly very poorly answered, despite asking for a relatively
standard chart. Candidates are reminded that where they have been unable to 
calculate the correct data for a chart, they may still gain marks for plotting “dummy” 
data.
Part (v) was the least well answered question in the whole paper. Few candidates 
provided appropriate comments. Candidates needed to focus their comments on 
whether the behaviour of the curves was in line with what they would have expected 
based on theoretical considerations. Comments that the curves were upward-sloping 
did not gain credit since this is the case for any distribution function. Where incorrect 
values were plotted in part (iv), marks were still awarded in part (v) for any 
appropriate comments consistent with what was plotted.


---