---
title: "Statistics with R"
subtitle: "Introduction to R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---


1 Before answering this question, the R package for Markov chains should be loaded 
into R using the following code: 
install.packages("markovchain") 
library(markovchain)
Xt is a Markov chain on the state space {1,2,3} with the following transition matrix: 
൭
p 1 – p 0
q 0 1 – q
0 r 1 – r
൱
where 0 < p, q, r < 1. 
(i) Construct an R function, with arguments p, q and r, that generates a Markov 
chain object for Xt. [5] 

------------------

Q1
(i)
markovchain = 
function(p,q,r){ 
 

P = matrix(data = c(p,1-p,0,q,0,1-q,0,r,1-r),
nrow =3, byrow = TRUE) 
 

mc = new("markovchain", transitionMatrix = P) [1½]
mc} 
 

(ii)
statdist = matrix(data = 0, nrow = 3, ncol = 9) 
 

for(i in 1:9){ 
 

q = 0.1*i 
 

mc = markovchain(p = 0.75, q, r = 0.25) 
 

statdist[,i] = steadyStates(mc)} 
 

statdist 
 

 [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
[1,] 0.08 0.16 0.24 0.32 0.4 0.48 0.56 0.64 0.72
[2,] 0.20 0.20 0.20 0.20 0.2 0.20 0.20 0.20 0.20
[3,] 0.72 0.64 0.56 0.48 0.4 0.32 0.24 0.16 0.08

 

 Assume that p = 0.75 and r = 0.25. 
(ii) Construct R code that calculates the stationary distribution of Xt for values of 
q from 0.1 to 0.9 inclusive, at intervals of 0.1, pasting your results into your 
answer script. [7] 
(iii) Plot a graph showing the stationary distributions of Xt calculated in part (ii) as 
a function of q. You should include three separately coloured lines on your 
graph, each line representing the stationary probabilities of each state. [8] 
 [Total 20] CS2B A2021–3 

(iii)
q = seq(from = 0.1, to = 0.9, by = 0.1) 
 

plot( 
 

q, 
 

statdist[1,], 
 

type = "l", 
 

main = "Stationary Distributions of X_t as a
function of q", 
 

ylab = "Probability", 
 

col = "red") 
 

lines(q, statdist[2,], col = "black") 
 

lines(q, statdist[3,], col = "blue") 
 

legend("top", 
legend = c("State 1", "State 2", "State 3"), 
 

col = c("red", "black", "blue"), 
 

pch=7)



 

[Total 20]
Part (i) was very well answered although some candidates lost marks for not creating 
a function, or for creating a function outputting a matrix rather than a Markov chain 
object. Candidates who did not create a function or who created a function outputting 
a matrix rather than a Markov chain object needed to perform additional work in part 
(ii). 
Part (ii) was well answered. Candidates who were less familiar with loops in R 
included more extensive R code than necessary. Candidates who answered part (ii) by 
raising the transition matrices to a large power were required to raise the matrices to 
a second large power to demonstrate convergence otherwise only partial credit was 
awarded.
Part (iii) was poorly answered. Many candidates lost marks for missing or 
inappropriate titles, axis labels and/or legends. Where candidates were unfamiliar 
with the legend function in R, a manually applied legend was accepted provided that it 
correctly represented the line colours and was situated next to the chart.


