---
title: "Statistics with R"
subtitle: "Introduction to R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(knitr)
library(dplyr)
library(janitor)


```

```{css, echo=FALSE}
pre {
  background: #ADD8E6;
  max-width: 100%;
  overflow-x: scroll;
}
```

* Introduction to R for Actuarial Students

* CS1B Curriculum

* Introduction to R programming
* Fundamentals of Statistical Analysis

* Question 1
---


1 (i) Simulate 10,000 values from a N(0,1) distribution using an appropriate R 
command. You should save the generated values in R for later use. [1] 
(ii) Simulate 10,000 values from a χ4
2 distribution using an appropriate R 
command. You should save the generated values in R for later use. [2] 
(iii) Discuss the main disadvantage of using the inverse transform method for 
simulating values from a chi-square distribution. [3] 
(iv) Simulate 10,000 values from a t4 distribution using your answers to parts (i) 
and (ii), explaining your answer. 
You should save the generated values in R for later use. [5] 
(v) Simulate 10,000 values from a t20 distribution by modifying your R code from 
parts (i), (ii) and (iv) where necessary. 
You should save the generated values in R for later use. [5] 
(vi) Demonstrate an important property of the t distribution by presenting and 
comparing two appropriate plots of the values simulated in parts (iv) and (v). 
 [6] 
 [Total 22] 

**1. Simulation and Analysis**

**1(i) Simulating N(0,1) values:**

```R
set.seed(123)  # For reproducibility
n <- 10000
z <- rnorm(n, mean = 0, sd = 1)
```

**1(ii) Simulating χ²₄ values:**

```R
chi_squared <- rchisq(n, df = 4)
```

**1(iii) Disadvantage of Inverse Transform Method for χ²:**

The inverse transform method requires finding the inverse cumulative distribution function (CDF) of the chi-square distribution. For the chi-square distribution, this inverse CDF is not analytically tractable, making it computationally inefficient and potentially less accurate, especially for large degrees of freedom.

**1(iv) Simulating t₄ values:**

We can simulate t-distributed values using the formula:

```
t = z / sqrt(chi_squared/df)
```

where `z` is a standard normal random variable and `chi_squared` is a chi-square random variable with `df` degrees of freedom.

```R
t4 <- z / sqrt(chi_squared/4)
```

**1(v) Simulating t₂₀ values:**

```R
t20 <- z / sqrt(chi_squared/20)
```

**1(vi) Demonstrating a Property of the t-distribution:**

As the degrees of freedom increase, the t-distribution approaches a standard normal distribution. We can visualize this by plotting the densities of the t₄ and t₂₀ distributions:

```R
library(ggplot2)

# Create a data frame to hold the simulated values
df <- data.frame(t4 = t4, t20 = t20)

# Melt the data frame for easier plotting
df_melted <- reshape2::melt(df)

# Plot the densities
ggplot(df_melted, aes(x = value, color = variable)) +
  geom_density() +
  labs(title = "Density Plots of t4 and t20 Distributions",
       x = "Value", y = "Density")
```

This plot will show that the t₂₀ distribution is more concentrated around 0 and has a shape closer to a normal distribution compared to the t₄ distribution.
