[Total 16]
CS1B S2019–45
The data given in the file policies_data.RData show the numbers of policies
(n.policies) by sex of policyholder (sex.code; 1 for male, 2 for female)
and class of business (class.code; 5 different classes) from a certain insurance
portfolio.
(i)
(a)
Construct a plot of the logarithm of the number of policies (on the y
axis) against the class of business.
(b)
Comment on the relationship in the data based on your plot in
part (i)(a).

In the plot produced in part (i) we can distinguish between male and female
policyholders. The plot is shown below, with “M” and “F” showing male and female
policyholders respectively:
(ii)
Comment on the relationship in the data based on this plot.

For the remainder of the question you will need to ensure that the sex and class
variables are treated as categorical variables (factors). You can use the following R
code:
class.code = as.factor(class.code)
sex.code = as.factor(sex.code)

(iii) Fit a generalised linear model analysis to the data, using a Poisson distribution,
with the numbers of policies as the response variable and the class of business
as the only factor. Your answer should include estimates of the parameters,
corresponding p-values and a brief interpretation of their effect.




END OF PAPER
CS1B S2019–6


Q5
(i)
(a)
load("policies_data.RData")
plot(log(n.policies) ~ class.code, pch=19,main = "Number
of policies against class of business")


(b)
There seems to be some dependence of number of claims on class of business
S 2019

with lower numbers for classes 4 and 5.
The relationship is not clear though.


(ii) It now seems that the number of claims also depends on the gender of policyholders.

The numbers are generally higher for males.

(iii) R code:
class.code = as.factor(class.code)
sex.code = as.factor(sex.code)
glm1 = glm(n.policies ~ class.code, family = "poisson")

summary(glm1)

#Coefficients:
#
Estimate
# (Intercept)
3.7257
# class.code2
0.1029
# class.code3
0.2540
# class.code4 -0.2917
# class.code5 -0.3935
Pr(>|z|)
<2e-16
0.4965
0.0825
0.0822
0.0229
***
.
.
*
Parameter estimates and their p-values are shown above.
Business class 1 is used as the baseline category (intercept level).

The effect of class 5 on the number of policies appears to be significantly different
from that of class 1, and there is some (weak) evidence that classes 3 and 4 also have
a different effect.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


```R

(iv) Fit a second Poisson generalised linear model analysis to the data, using the
numbers of policies as the response variable and both the class of business and
the sex of the policyholders as factors. Your answer should include estimates
of the parameters, corresponding p-values and a brief interpretation of their
effect.

CS1B S2019–5

(v) Determine, using the deviance, which of the two models used in parts (iii)
and (iv) provides a better fit to the data. Your answer should include the null
hypothesis, the p-value of the relevant test and a clear conclusion.

(vi) Calculate the predicted number of policies for male policyholders when the
class of business is 2, based on the model chosen in part (v).

[Total 32]


```


```R

(iv)
R code:
glm2 = glm(n.policies ~ class.code + sex.code, family =
"poisson")

summary(glm2)

#Coefficients:
#
Estimate
#(Intercept)
3.8611
#class.code2
0.1029
#class.code3
0.2540
#class.code4 -0.2917
#class.code5 -0.3935
S 2019
Pr(>|z|)
< 2e-16
0.49648
0.08248
0.08225
0.02288
***
.
.
*
#sex.code2
-0.2921
0.00386 **
Numbers of policies depend on both business class and gender of policyholder.

Business class 5 has the strongest effect on number of policies when compared to
class 1, and this effect is negative (reducing number of policies). Male policyholders
give the baseline here, so being female has a significant negative effect on number of
policies.

(v)
The null hypothesis is that the second model (including both factors) is not an
improvement over the first model.

R code:
anova(glm1,glm2,test = "Chisq") 
#Model 1: n.policies ~ class.code
#Model 2: n.policies ~ class.code + sex.code
# Resid. Df Resid. Dev Df Deviance Pr(>Chi)
#1
5
14.2560
#2
4
5.8163 1
8.4397 0.003671 ** 
The p-value is 0.003671. 
Therefore we have strong evidence against the null hypothesis. We conclude that the
second model gives significant improvement.

(vi)
R code:
predict(glm2, data.frame(class.code="2", sex.code="1"),
type="response")

Based on model 2 we predict 52.67 policies.

[Total 32]
The performance in this question was mixed. Part (i) was generally well answered, but the
comments in (b) were often insufficient. In part (ii) there was a range of comments of
varying validity. In parts (iii) and (iv) many candidates fitted the GLM successfully but
produced weak comments. Note that part (iv) can alternatively be answered using the
update() command. Parts (v) and (vi) were not well answered, with a number of
candidates failing to use the deviance as requested and instead opting for the AIC.
END OF EXAMINERS’ REPORT
S 2019

```
