---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---


Let ${\displaystyle Z}$ be a standard normal variable, and let ${\displaystyle \mu }$ and ${\displaystyle \sigma &gt;0}$ be two real numbers. Then, the distribution of the random variable

$${\displaystyle X=e^{\mu +\sigma Z}} $$
is called the log-normal distribution with parameters ${\displaystyle \mu }$  and ${\displaystyle \sigma }$. 

\begin{center}
\begin{tabular}{cc}
***Mean***	& ${\displaystyle \exp \left(\mu +{\frac {\sigma ^{2}}{2}}\right)} $\\
***Variance***	& ${\displaystyle [\exp(\sigma ^{2})-1]\exp(2\mu +\sigma ^{2})} $\\
\end{tabular}
\end{center}


\begin{verbatim}

exp(0.5)


exp(2 +((0.5)^2/2 ))
\end{verbatim}




Comment on the appropriateness of the central limit theorem by implementing the following steps:

---

\subsection*{Exercise 1}

Generate a sample of 10000 random observations following Lognormal distribution with parameters μ = 2 and σ 2 = 0.25 

Display the first few simulated observations using the head (...) function. 

[Use a seed value of 100 to generate random numbers] 

\begin{verbatim}

# Generate a random sample from a Lognormal distribution

set.seed(100)

data1<-rlnorm(10000,meanlog = 2,sdlog = 0.5)

# First 6 observations are shown below

head(data1)
##  5.748298 7.891337 7.103172 11.512028 7.834097

\end{verbatim}


\begin{verbatim}
mean(data1)    
\end{verbatim}

---

\subsection*{Exercise 2}
\large 
\noindent Compute the sample mean, median and variance from the generated sample and compare the values with those of a population following a lognormal distribution with the given
parameters. 


\begin{framed}
\begin{verbatim}
# Compute the mean, median and variance of the sample
mean(data1)
##  8.375649
median(data1)
##  7.398463
var(data1)
##  19.51361
\end{verbatim}
\end{framed}

---

\begin{framed}
\begin{verbatim}
# Formula based mean values
mean<-exp(2+0.25/2)
median<-exp(2)
var<-(exp(0.25)-1)*exp(2*2+0.25)
mean
##  8.372897 
Median 
##  7.389056
var

##  19.91172
\end{verbatim}
\end{framed}

Interpretation: 

Mean, Median and Variance of the generated sample and those computed based on the parameters are almost equal because the sample size is 10,000 which is pretty large. 

Generating a much larger sample will bridge those smaller differences existing between them as well


---

\subsection*{Exercise 3}

\noindent  Treat the data generated in (i) as the population. Generate 500 different random samples
of size 200 from the above population and compute the sample mean for each sample.
[Use a seed value of 100 to generate random numbers] (5)


\begin{framed}
\begin{verbatim}
    
set.seed(100);
data1<-rlnorm(10000,meanlog = 2,sdlog = 0.5)

means <- replicate(5000,
    mean(sample(data1,200,replace=FALSE)))
\end{verbatim}
\end{framed}


\begin{framed}
\begin{verbatim}
#Generating 500 different samples of size 200
#Then computing their sample means

means<-c()

set.seed(100)
for (i in 1:500){
    selected_rows<-sample(1:10000,200,FALSE)
    selected_data<-data1[selected_rows]
    sample_mean<-mean(selected_data)
    means<-c(means,sample_mean)
} 

\end{verbatim}
\end{framed}


---

\subsection*{Exercise 4}
\noindent Plot the histogram of sample means generated from part (iii) and interpret the distribution
of sample means.


\begin{framed}
\begin{verbatim}
#Histogram of Sample Means
hist(means,breaks = 30) 
\end{verbatim}
\end{framed}

Interpretation: The sample means tend to follow a normal distribution though the actual data
comes from lognormal distribution. Central limit theorem can be verified through this
exercise that sample means tend to follow a normal distribution as the sample size increases.
Increase in Sample size from 200 to much higher can ensure better normality of the sample
means

