\documentclass[a4paper,12pt]{article}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\usepackage{eurosym}
\usepackage{vmargin}
\usepackage{amsmath}
\usepackage{graphics}
\usepackage{epsfig}
\usepackage{enumerate}
\usepackage{multicol}
\usepackage{subfigure}
\usepackage{fancyhdr}
\usepackage{listings}
\usepackage{framed}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{chngpage}
%\usepackage{bigints}

\usepackage{vmargin}
% left top textwidth textheight headheight
% headsep footheight footskip
\setmargins{2.0cm}{2.5cm}{16 cm}{22cm}{0.5cm}{0cm}{1cm}{1cm}
\renewcommand{\baselinestretch}{1.3}

\setcounter{MaxMatrixCols}{10}

\begin{document}



\begin{framed} \begin{verbatim}
Question 5

Refer to the data file “Indices_Returns.csv” and answer the following questions:

Indices_Returns.csv file is provided in the system.

indices<-read.csv("D:\\Indices_Returns.csv")
\end{verbatim}\end{framed}


\begin{framed} \begin{verbatim}

i) Load the csv file into R and create a new column called “Sensex_Direction”. 

The value of this column will be “Positive” when the Sensex returns are positive and “Negative” when they are negative and convert the variable as a factor variable. 
\end{verbatim}\end{framed}


\begin{framed} \begin{verbatim}

# Creation of new column called Sensex_Direction

indices$Sensex_Direction <-     ifelse(indices$Sensex>0,"Positive","Negative")

indices$Sensex_Direction <- as.factor(indices$Sensex_Direction)

\end{verbatim}\end{framed}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage 
\subsection*{Exercise 2}

Fit an appropriate generalized linear model (GLM) to with a ‘logit’ link function to relate the “Sensex_Direction” with the returns of 10 sectors as a multivariate model and display
the summary of the model. 



\begin{framed} \begin{verbatim}
# Fit the model and display the summary
model1 <- glm( Sensex_Direction ~ BM+CD+EN+FI+FM+HC+IN+IT+TE+UT,
               data = indices, 
               family = binomial(link = "logit"))

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred
summary(model1)



\end{verbatim}\end{framed}
%%%%%%%%%%%%%%%%%%%%%%%%%%%5
\newpage 
## Exercise 

Identify which sectors have significantly impacted the direction of Sensex returns at 95% and 99% confidence level.

Verify the relationship between residual deviance of the model and the Akaike Information Criteria (AIC). 


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5
\newpage
\subsection*{Exercise 3}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5
\newpage
\subsection*{Exercise 4}


Sectors significantly impacted
 Sectors which have significantly impacted the direction of Sensex retur
ns are CD, EN, FI, FM, IT and TE at 95% Confidence level

 But only FI has impacted the Sensex direction at 99% Confidence level


Relationship between the residual deviance and AIC
 all.equal(AIC(model1), model1$deviance+2*11)
 (11 number of model parameters (the number of variables in the model pl
us the intercept))


\end{document}
