[35]
Q. 3) A General Insurance company is trying to analyse the two-wheeler motor insurance claims 
reported over last one quarter.
The data is provided herewith the file MotorClaim.csv which contains the following fields
POLICY: Policy Number
CLAIM : Amount of claim reported for a policy
Insurance Company is interested to find out an appropriate distribution to fit the “CLAIM” 
data. You are being asked to find out the appropriateness of the following distributions 
based on method of moments:
1. Normal distribution
2. Lognormal distribution
3. Exponential distribution
4. Gamma distribution.
########################
 Page 4 of 4
i) Estimate the parameters of each of the above distributions. (8)
ii) Plot a histogram of “CLAIM” data with 35 equal class intervals. Superimpose the 
histogram with the probability density function of the above four distributions using 
their estimated parameters as obtained in part (i). Mark each plot distinctly using 
appropriate legend. (8)
iii) Compute the 5th percentile, 1st quartile, median, 3rd quartile and 95th percentile of both 
the actual claim paid as well as the fitted distributions. (5)
iv) Using the results from (ii) and (iii) comment on goodness of fit of the models to the 
data. (4)
v) Assuming Gamma distribution to be the right fit to the data, simulate 20,000 values of 
claim amounts using the Gamma distribution based on the parameter estimates 
obtained in part (i) and print first 10 values of claim amounts. (Set seed to 2022) (2)
vi) Generate 700 different random samples of size 400 from the simulated data obtained 
in part (v) and compute sample mean for each of the samples. (Set seed to 2022) (5)
vii)Plot the histogram of sample means generated from part (vi) and comment on the 
distribution of the sample means from the point of view of central limit theorem. (3)
[35]
*****************************

[35 Marks]
Solution 3:
# Sample mean and variance
Motorclaim = read.csv("Motorclaim.CSV")
Mean_Claim<-mean(Motorclaim$CLAIM)
Var_Claim<-var(Motorclaim$CLAIM)
i)
# Method of moments estimate
# Normal Distribution
Normal_mu <- Mean_Claim 
Normal_sigma <- sqrt(Var_Claim) 
Normal_mu
[1] 6357.314 
Normal_sigma
[1] 6986.523 
# Log Normal Distribution
LogNormal_sigma<- sqrt(log(1+Var_Claim/Mean_Claim^2)) 
LogNormal_mu<-log(Mean_Claim)-LogNormal_sigma^2/2 
########################
Page 10 of 13
LogNormal_sigma
[1] 0.8899276 
LogNormal_mu
[1] 8.361376 
# Exponential Distribution
Exp_lamda <- 1/Mean_Claim 
Exp_lamda
[1] 0.0001572991 
# Gamma Distribution
Gamma_lamda<-Mean_Claim/Var_Claim 
Gamma_alpha<-Gamma_lamda*Mean_Claim 
Gamma_lamda
[1] 0.0001302421 
Gamma_alpha
[1] 0.82799 
(8)
ii)
# Histogram
hist(Motorclaim$CLAIM,breaks = 35,freq = FALSE) 
#Superimpose Normal distribution
curve(dnorm(x,mean = Normal_mu,sd = Normal_sigma),from = min(Motorclaim$CLAIM), to = 
max(Motorclaim$CLAIM), add = TRUE, col= "blue") 
#Superimpose Log Normal distribution
curve(dlnorm(x,meanlog = LogNormal_mu,sdlog = LogNormal_sigma),from = 
min(Motorclaim$CLAIM), to = max(Motorclaim$CLAIM), add = TRUE, col= "green") 
#Superimpose Exponential distribution
curve(dexp(x,rate = Exp_lamda),from = min(Motorclaim$CLAIM), to = max(Motorclaim$CLAIM), add 
= TRUE, col= "red") 
#Superimpose Gamma distribution
curve(dgamma(x,shape = Gamma_alpha,rate = Gamma_lamda),from = min(Motorclaim$CLAIM), to 
= max(Motorclaim$CLAIM), add = TRUE, col= "yellow") 
legend("topright",legend = c("Normal", "Lognormal", "Exponential", "Gamma"),lty = 1, col = 
c("blue","green","red","yellow"))
########################
Page 11 of 13
 
 (8)
iii)
# Quantiles 
# Actual Claim Data
quantile(Motorclaim$CLAIM,c(0.05,0.25,0.5,0.75,0.95)) 
 5% 25% 50% 75% 95% 
1324.561 1934.876 3631.070 7870.028 21246.913 
 
# Normal Distribution
qnorm(c(0.05,0.25,0.5,0.75,0.95),mean = Normal_mu,sd = Normal_sigma) 
[1] -5134.494 1644.976 6357.314 11069.653 17849.123 
# Log Normal Distribution
qlnorm(c(0.05,0.25,0.5,0.75,0.95),meanlog = LogNormal_mu,sdlog = LogNormal_sigma) 
[1] 989.8714 2347.5526 4278.5767 7798.0014 18493.5327 
# Exponential Distribution
qexp(c(0.05,0.25,0.5,0.75,0.95),rate = Exp_lamda) 
[1] 326.0876 1828.8853 4406.5544 8813.1089 19044.8114 
########################
Page 12 of 13
# Gamma Distribution
qgamma(c(0.05,0.25,0.5,0.75,0.95),shape = Gamma_alpha,rate = Gamma_lamda) 
[1] 193.6261 1479.4200 4053.4299 8797.0450 20369.6614 
(5)
iv) From the histogram and superimposed plots it is clear that normal distribution is not good fit to 
the data. 
The other three plots are getting superimposed more or less similar to the data. From the quantiles it 
is observed that lower value(5th percentile) of lognormal is closed to actual value and higher 
values(95th percentile) of gamma distribution is closed to actual value 
The best fitting distribution among Lognormal, exponential & Gamma can not be decided basis of 
observations from (ii) & (iii). Further statistical tests need to be carried out to confirm best fit 
(4)
v)
# Simulation from Gamma distribution
set.seed(2022) 
Sim_samples <- rgamma(20000,Gamma_alpha,Gamma_lamda) 
head(Sim_samples,10) 
[1] 9505.735311 1376.831631 458.302589 3189.065594 5.340363 5821.017458
[7] 11122.004509 5372.490004 43002.362493 3557.086406 
(2)

##########################################################
vi)
# Generating 700 random samples of size 400 and computing sample means 
means<-c()
set.seed(2022)
for (i in 1:700){
selected_data_point<-sample(1:20000,400,FALSE)
random_sample<- Sim_samples[selected_data_point]
sample_mean<-mean(random_sample)
means<-c(means,sample_mean)
} 
(5)
vii)
# Histogram of the sample means
hist(means,breaks = 40)
########################
Page 13 of 13
Comment:
The distribution of sample means tend to follow normal distribution however the actual data comes 
from gamma distribution. Central Limit Theorem states that the sample means tend to follow 
normal distribution as the sample size increases. The distribution of sample means will be closer to 
normal distribution by increasing the sample size from its current level of 400. 
 (3)
[35 Marks]
***************************