---
title: "Statistics with R"
subtitle: "Modelling Data with R"
author: "Dragonfly Stats"
date: "2016/12/12"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

[Total 22] CS1B A2021–4 
3 A study was carried out to estimate the proportion, 𝑝, of workers that commute by 
train to work. A total of n ൌ 200 workers were sampled at random and were asked the 
question: ‘Do you take the train to work?’ The workers’ answers were recorded as a 
binary outcome, yi, for worker i, with 1 for yes and 0 for no. The data are available in 
the file BinaryTrain.RData.

---

Two commuters, Alice and Norman, were interested in the study and proposed 
different prior distributions for the proportion p. 
Alice assumed a discrete prior distribution g(p) given in the following table: 
p 0.1 0.2 0.3 0.4 0.5 
g(p) 0.5 0.2 0.2 0.05 0.05 
Norman chose to use a beta prior distribution for p, with parameters 3 and 12. 

---

Part 1
=========================================
(i) (a) Calculate the mean and the standard deviation for Alice’s prior
distribution. [4] 
(b) Generate 10,000 random values from Norman’s prior distribution. [1] 
(c) Calculate the mean and standard deviation of the values generated in
part (i)(b). [2] 
(d) Comment on whether or not Alice and Norman have similar prior 
beliefs for p. 

---


Norman’s beta prior distribution for p is adopted for the remainder of the question. 


* The likelihood of the model in the study is given by: 
Lሺpሻ ∝ p∑ yi ሺ1 – pሻn – ∑ yi . 
* The posterior density of p is given by: 
f(p|y) ∝ p2 + ∑ yiሺ1 – pሻ11 + n – ∑yi ,
where ∑ yi is the total sum of all the binary data. 

---

Part 2
=========================================
(ii) Plot the shape of the posterior density of p without identifying it.  
(iii) Plot the density of Norman’s prior distribution by setting ylim = c(0,14). 
 [3] 
The posterior distribution of p is beta with parameters 3 + ∑ yi and 12 + n – ∑ yi
. 

---

Part 4
=========================================
(iv) (a) Plot the posterior density of p by adding it to the plot in part (iii). 
(b) Compare the two densities using your answer in part (iv)(a). 
(c) Comment on the extent to which the posterior distribution is affected 
by the prior distribution. [1] CS1B A2021–5 
(v) Determine a 90% interval estimate for p based on its posterior distribution. 


---

Part 6
=========================================
(vi) Determine the exact posterior probability that p exceeds 0.25. [2] 
(vii) (a) Generate 10,000 samples from the posterior distribution of p. 
(b) Calculate the proportion of sampled values of p that exceed 0.25. 
(c) Compare your answer in part (vii)(b) with your answer in part (vi). 
