---
title: "Statistics with R"
subtitle: "Statistical Modelling with R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(knitr)
library(dplyr)
library(janitor)

options(scipen = 2, digits = 3) #set to two decimal 
```

```{css, echo=FALSE}
pre {
  background: #ADD8E6;
  max-width: 100%;
  overflow-x: scroll;
}
```


***CS2B – Risk Modelling and Survival Analysis ***


* The emphasis is placed on being able to apply statistical methods to actuarial problems using real data sets and the open-source software environment R. 

* Time Series. Probability Distributions, Survival Analysis

---

2 A life insurance company has issued a 1-year group insurance policy covering 10,000
employees categorized into four age bands of 2,500 employees each.
The following amounts are paid upon each death under the policy:
 Death from pandemic diseases mentioned in the policy document: £80,000.
 Death from cause other than above: £40,000.
The premium charged for each group was estimated as the mean of a compound
binomial distribution.
The ‘CS2B_A23_Qu_2_Data.csv’ file contains the following data for each group:
group: name of the group
age_band: age range in the group
Mort: expected probability of death
p_dth: proportion of deaths due to pandemic diseases
Before answering this question, the ‘CS2B_A23_Qu_2_Data.csv’ file should be
loaded into R and assigned to a data frame called ‘Prem’.
(i) Calculate the premium that company would have charged under each of the
groups, ignoring expenses and profit margin, assigning your output to a vector
called ‘Prem_charged’ and displaying ‘Prem_charged’ in your answer script.
[6]
The head of the department wishes to project the actual claims over the next year
using random numbers.
(ii) Generate a sample of size 2,500 under each of the above groups from a
Bernoulli distribution, simulating whether death occurs for each of the
employees using the expected probability of death from the table ‘Prem’. You
should output your results to a data frame called ‘Tab_R’ consisting of four
column vectors ‘G1_R’to ‘G4_R’. The random number generator seed to be
used is 123.
Use the summary() function to display your results. [6]
(iii) Generate a data frame ‘Tab_U’ of observations from the Uniform(0,1)
distribution, consisting of four column vectors, ‘G1_U’ to ‘G4_U’, with 2,500
components each. The random number generator seed to be used is 300. Use
the R function head(), to display the first six rows of ‘Tab_U’. [4]
CS2B A2023–5
(iv) Generate a data frame ‘Tab_V’, consisting of four column vectors ‘G1_V’ to
‘G4_V’, with 2,500 components each, representing claim amounts under each
group.
If death has occurred, the relevant entry of ‘Tab_V’ should be set to 80,000 if
the random variable generated in part (iii) is less than or equal to the
proportion of pandemic deaths specified in the table ‘Prem’ for the relevant
group, or 40,000 otherwise.
Use the summary() function to display your results. [8]
(v) Calculate the aggregate claim amount under each group, displaying your
output as a vector. [3]
(vi) Calculate the projected profit or loss under each group and the policy as a
whole. 
One of the employees suggests that the premium rate charged should be based on the
actual claims obtained from part (v) above.
(vii) Comment on the validity of the employee’s suggestion, assuming that the
distribution used, the parameters used and the methodology adopted are
reasonable. [4]
[Total 33]
CS2B A2023–6
