

```{r}
Q. 4)

An life insurance company is selling Endowment, Pure Term and Unit Linked products
wherein 80% of the business comes from Endowment, 5% from Term Insurance and 15%
from Unit Linked products. The sum assured ranges between 30000 to 200000 with multiple
of 5000 . The sum assured are normally distributed with below parameters - Endowment
(mean 50000, standard deviation 10000), Pure Term (mean 100000, standard deviation
25000), Unit Linked (mean 60000, standard deviation 5000). One policy is randomly picked
from the system and the sum assured of that policy is 75000.
Page 2 of 4IAI

1. 
Create a sequence ranging from 30000 to 200000 with an increase of 5000 and plot the
density functions of the above three distributions in a single graph.
2.  Find the probability that the policy (75000 sum assured) comes from the Endowment
product portfolio and the probability that the policy comes from Unit Linked Product
portfolio.






```


```{r}

Solution 4:

[7 Marks]
1. 
y<-seq(30000,200000,5000)
y
FE<-dnorm(y,50000,10000)
FPT<-dnorm(y,100000,25000)
FUL<-dnorm(y,60000,5000)
plot(y,FE,typ="l",col="darkgreen",lwd=2)
lines(y,FPT,col="darkred",lwd=2)
lines(y,FUL,col="darkblue",lwd=2)
> y
 30000 35000 40000 45000 50000 55000 60000 65000 70000 75000
80000
[12] 85000 90000 95000 100000 105000 110000 115000 120000 125000 130000
135000
[23] 140000 145000 150000 155000 160000 165000 170000 175000 180000 185000
190000
[34] 195000 200000
```


```{r}

2. 
PE<-0.8
PPT<-0.05
PUL<-0.15
PxE<-dnorm(75000,50000,10000)
PxPT<-dnorm(75000,100000,25000)



PxUL<-dnorm(75000,60000,5000)
P1<-PE*PxE / (PE*PxE+PPT*PxPT+PUL*PxUL)
P2<-PUL*PxUL / (PE*PxE+PPT*PxPT+PUL*PxUL)
P1
P2

> P1
 0.6944786
> P2
 0.06584688
[4]

[12 Marks]
```
