
A researcher has collected the following data on a group of students, regarding
whether they passed or failed an exam and whether or not they attended tutorials:
Number of students Exam passed Exam failed
Attended tutorials 132 27
Did not attend tutorials 120 51
The data can be entered into R in matrix form using the following code:
exam.success = matrix(c(132,120,27,51),ncol=2,nrow=2)
The reasercher wants to establish whether tutorial attendance is independent of exam
success, using a chi-square test.


---

Questions
======================================================
(i) State the hypotheses of this test. 
(ii) Calculate the expected frequencies for the data under the null hypotheses
in part (i). 
(iii)
Perform the test stating clearly your conclusion.
CS1B S2020–2


Questions
======================================================

# set up the data matrix
exam.success = matrix(c(132,120,27,51),ncol=2,nrow=2)
# print data matrix to check for errors
exam.success
[,1] [,2]
[1,] 132
27
[2,] 120
51
(i)
The null hypothesis being tested is that tutorial attendance and exam success are independent,
against
the alternative that they are not independent.

Part 2
======================================================
(ii)
# run chi-square test and extract expected frequencies
chisq.test(exam.success)$expected
[,1]
[,2]
[1,] 121.4182 37.58182
[2,] 130.5818 40.41818


(iii)
------------------------------------

# run chi-square test, removing the Yates' continuity
correction

chisq.test(exam.success, correct=FALSE)
Pearson's Chi-squared test
data: exam.success
X-squared = 7.5296, df = 1, p-value = 0.006069

The p-value is significant (e.g. at the 1% level), since 0.006069 < 0.01 – therefore there is
evidence to reject the null hypothesis and we conclude that tutorial attendance and exam
success are not independent.

[Total 11]
Part (i) was well performed. Answers in part (ii) were mixed, with a number of candidates
not attempting this part, or using manual derivations containing various errors. Part (iii)
was well answered. Note that including the Yates' continuity correction was not penalised
here.
