---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---


Q. 3) The following graph shows the relationship between the first premium paid and the ratio of
Maturity/Death SA to the first premium of several policies whose term is 20 years.
SA - Premium Relations
300
250
200
150
100
50
0
0
50
100
150
200
250
300
350
400
450
First Premium in 1000s
i)
ii)
Devise a binary decision tree that can be used to identify the nature of a policy – Regular
Premium, Regular Limited Payment and Single Premium - based only on their First
Premium paid and the Death/Maturity SA (assuming that Death and Maturity SA are
the same) and the policy term is 20 years. (4)


---

Solution 3:
i) For the same sum assured, the single premium will be much higher than regular premium, therefore
the ratio of sum assured to first year premium will be smaller for single premium than regular
premium. The ratio for limited premium policies will be in between single premium and regular
premium.
It is observed that the ratio is above 150 means the policies are Regular Premium Policies and if the
ratio is below 50 means the policies are Single Premium Policies. If the ratio falls between 50 and 150
indicates that the policies are Regular Limited Payment Polices.

Binary Decision Tree:
IF ratio < 50
If ration > 150
If yes
If yes
Single Premium
Regular Payment
Regular Limited
Payment

---

Explain the reason behind the scales in the above graph. (2)

ii) Sum Assured are usually in lakhs/Crores and the Premium are usually quoted in thousands/lakhs.
So, if (Lakhs, thousands) are used as scales then the SA would totally dominate the calculations and
the premiums would effectively be ignored. However, if the SA and premium are converted to 100s
and 1000s respectively, then SA/Premium ratio provides a numerically similar scale for similar type
of policies.


---

CS2B - 0619
iii)
Also, write the R code for finding the nature of policy based on Binary decision tree
method.

 The following R code explain the binary decision tree:
 
```{r} 
SA<-5000000
FP<-250000
Ratio<-(SA/100)/(FP/1000)
guess<-ifelse(   Ratio<50,"Single Premium",ifelse(Ratio>150,"Regular Premium","Regular Limited
Premium"))
guess
guess

```