---
title: "Statistics with R"
subtitle: "R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---


\noindent An airport has recently introduced a driverless pod system to transport passengers
between the terminal and the car park. Pods operate every two minutes from
the terminal exit, and each pod can take up to two passengers and their luggage.
Passengers arrive at the terminal exit seeking to travel to the car park according to a
Poisson process with a rate of 1 per minute.
If four or more passengers are waiting at the exit when a pod arrives, taxis are
immediately summoned to take all the remaining passengers to the car park.

\subsection*{Exercise 1}
\noindent Calculate the probabilities that 0, 1, 2, 3, and 4 or more passengers will appear
at the exit to the terminal in any given two-minute period.




Q2
(i)

```{r}
dpois(0:3, 2)
```
 0.1353353 0.2706706 0.2706706 0.1804470
1 - ppois(3, 2)
 0.1428765
OR:
1-sum(dpois(0:3, 2))
 0.1428765
So the probabilities are:
0
1
2
3
4+
0.1353
0.2707
0.2707
0.1804
0.1429


\subsection*{Exercise 2}
(ii) Determine a transition matrix for the number of passengers waiting at the exit
when a pod arrives.



(ii)
0  0.1353
1   0.1353
2  0.1353

3  0
4 +   0.1353
0.2707
0.2707
0.2707
0.1353
0.2707
0.2707
0.2707
0.2707
0.2707
0.2707
0.1804
0.1804
0.1804
0.2707
0.1804
0.1429 
0.1429  
0.1429 

0.3233 
0.1429  


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage 
\subsection*{Part 3}
Calculate the average number of times per hour that the company operating the pods will need to summon a taxi to take passengers to the car park.
\begin{framed}
\begin{verbatim}
Passengers <- c("0", "1", "2", "3", "4+")
Passengers


PassMatrix <- matrix(c(0.1353, 0.2707, 0.2707, 0.1804, 0.1429, 
                       0.1353, 0.2707, 0.2707, 0.1804, 0.1429, 
                       0.1353, 0.2707, 0.2707, 0.1804, 0.1429, 
                       0, 0.1353, 0.2707, 0.2707, 0.3233, 
                       0.1353, 0.2707, 0.2707, 0.1804, 0.1429),
             nrow = 5, byrow = TRUE, 
             dimname = list(Passengers, Passengers))

PassMatrix
\end{verbatim}
\end{framed}





\begin{framed}
\begin{verbatim}

# if R package is not installed - requires recent version of R.
# install.packages("markovchain") 

library(markovchain)

Airport <- new("markovchain", 
               states = Passengers, 
               byrow = TRUE, 
               transitionMatrix = PassMatrix, 
               name = "Passengers waiting")    
\end{verbatim}
\end{framed}





Airport
Passengers waiting
A 5 - dimensional discrete Markov Chain defined by the
following states:
0, 1, 2, 3, 4+
The transition matrix (by rows) is defined as follows:
0
1
2
3
4+
0 0.1353 0.2707 0.2707 0.1804 0.1429
1 0.1353 0.2707 0.2707 0.1804 0.1429
2 0.1353 0.2707 0.2707 0.1804 0.1429
3 0.0000 0.1353 0.2707 0.2707 0.3233
4+ 0.1353 0.2707 0.2707 0.1804 0.1429

steadyStates(Airport)
0
1
2
3
4+
[1,] 0.108469 0.2438492 0.2707 0.1983071 0.1786746


So there will be four or more passengers waiting when 17.87 per cent of the pods arrive.
Since there are 30 pods arriving per hour, a taxi will need to be summoned an average of 5.36 times per hour.




OR:
Passengers <- c("0", "1", "2", "3", "4+")
Passengers
 "0" "1"
"2"
"3"
"4+"
PassMatrix <- matrix(c(0.1353, 0.2707, 0.2707, 0.1804,
0.1429, 0.1353, 0.2707, 0.2707, 0.1804, 0.1429, 0.1353,
0.2707, 0.2707, 0.1804, 0.1429, 0, 0.1353, 0.2707,
0.2707, 0.3233, 0.1353, 0.2707, 0.2707, 0.1804, 0.1429),
nrow = 5, byrow = T, dimname = list(Passengers,
Passengers))
PassMatrix
0
1
0 0.1353 0.2707
1 0.1353 0.2707
2 0.1353 0.2707
3 0.0000 0.1353
4+ 0.1353 0.2707

2
0.2707
0.2707
0.2707
0.2707
0.2707
3
0.1804
0.1804
0.1804
0.2707
0.1804
4+
0.1429
0.1429
0.1429
0.3233
0.1429



@Institute and Faculty of Actuaries - 

SteadyState <- diag(5)
for (i in 1:100){
SteadyState <- SteadyState %*% PassMatrix
}
SteadyState
0
1
2
3
4+
[1,] 0.108469 0.2438492 0.2707 0.1983071 0.1786746
[2,] 0.108469 0.2438492 0.2707 0.1983071 0.1786746
[3,] 0.108469 0.2438492 0.2707 0.1983071 0.1786746
[4,] 0.108469 0.2438492 0.2707 0.1983071 0.1786746
[5,] 0.108469 0.2438492 0.2707 0.1983071 0.1786746


Hence the steady states are:
0
1
2
3
4+
0.108469 0.2438492 0.2707 0.1983071 0.1786746



So there will be four or more passengers waiting when 17.87 per cent of the pods arrive.

Since there are 30 pods arriving per hour, a taxi will need to be summoned an average of 5.36 times per hour.


\newpage 
\subsection*{Exercise 4}

A manager at the airport has suggested that pods could be operated every 1.75 minutes without compromising safety, and that this would greatly reduce the
need to use taxis.

Evaluate the manager’s suggestion, showing any working where appropriate.


Repeat the analysis for pod frequency equal to 1.75 minutes.

dpois(0:3, 1.75) %>% round(3)

sum( dpois(0:3, 1.75) )




 0.1737739 0.3041044 0.2660914 0.1552200
1 - ppois(3, 1.75)
 0.1008103
OR:
1-sum(dpois(0:3, 1.75))
PassMatrix2 <- matrix(c(0.1738, 0.3041, 0.2661, 0.1552,
0.1008, 0.1738, 0.3041, 0.2661, 0.1552, 0.1008, 0.1738,
0.3041, 0.2661, 0.1552, 0.1008, 0, 0.1738, 0.3041,
0.2661, 0.2560, 0.1738, 0.3041, 0.2661, 0.1552, 0.1008),
nrow = 5, byrow = T, dimname = list(Passengers,
Passengers))
PassMatrix2


\begin{framed}
\begin{verbatim}
0
1
2
3
4+
0 0.1738 0.3041 0.2661 0.1552 0.1008
1 0.1738 0.3041 0.2661 0.1552 0.1008
2 0.1738 0.3041 0.2661 0.1552 0.1008
3 0.0000 0.1738 0.3041 0.2661 0.2560
4+ 0.1738 0.3041 0.2661 0.1552 0.1008
\end{verbatim}
\end{framed}

\begin{framed}
\begin{verbatim}
Airport2 <- new("markovchain", states = Passengers,
byrow = T, transitionMatrix = PassMatrix2, name =
"Passengers waiting")    
\end{verbatim}
\end{framed}

Airport2
Passengers waiting
A 5 - dimensional discrete Markov Chain defined by the
following states:
0, 1, 2, 3, 4+
The transition matrix (by rows) is defined as follows:
0
1
2
3
4+
0 0.1738 0.3041 0.2661 0.1552 0.1008
1 0.1738 0.3041 0.2661 0.1552 0.1008
2 0.1738 0.3041 0.2661 0.1552 0.1008
3 0.0000 0.1738 0.3041 0.2661 0.2560
4+ 0.1738 0.3041 0.2661 0.1552 0.1008



steadyStates(Airport2)
0
1
2
3
4+
[1,] 0.1434617 0.281355 0.2727332 0.1745585 0.1278915


Taxis will be needed when 12.79 per cent of the pods arrive.
There are 34.28 pods per hour, so 4.38 taxis per hour will be required.

OR:
dpois(0:3, 1.75)
 0.1737739 0.3041044 0.2660914 0.1552200
1 - ppois(3, 1.75)
 0.1008103
OR:
1-sum(dpois(0:3, 1.75))
PassMatrix2 <- matrix(c(0.1738, 0.3041, 0.2661, 0.1552,
0.1008, 0.1738, 0.3041, 0.2661, 0.1552, 0.1008, 0.1738,
0.3041, 0.2661, 0.1552, 0.1008, 0, 0.1738, 0.3041,
0.2661, 0.2560, 0.1738, 0.3041, 0.2661, 0.1552, 0.1008),
nrow = 5, byrow = T, dimname = list(Passengers,
Passengers))

\newpage 


Matrix2
0
1
0 0.1738 0.3041
1 0.1738 0.3041
2 0.1738 0.3041
3 0.0000 0.1738
4+ 0.1738 0.3041
2
0.2661
0.2661
0.2661
0.3041
0.2661
3
0.1552
0.1552
0.1552
0.2661
0.1552
4+
0.1008
0.1008
0.1008
0.2560
0.1008
SteadyState2 <- diag(5)
for (i in 1:100){
SteadyState2 <- SteadyState2 %*%
}
SteadyState2
0
1
2
[1,] 0.1434617 0.281355 0.2727332
[2,] 0.1434617 0.281355 0.2727332
[3,] 0.1434617 0.281355 0.2727332
[4,] 0.1434617 0.281355 0.2727332
[5,] 0.1434617 0.281355 0.2727332

PassMatrix2
3
0.1745585
0.1745585
0.1745585
0.1745585
0.1745585
4+
0.1278915
0.1278915
0.1278915
0.1278915
0.1278915

Hence the steady states are:
0
1
2
3
4+
0.1434617 0.281355 0.2727332 0.1745585 0.1278915




\begin{itemize}
    \item Taxis will be needed when 12.79 per cent of the pods arrive.
    \item There are 34.28 pods per hour, so 4.38 taxis per hour will be required. 
    \item Increasing the frequency of pods from 30 to 34.28 per hour (a 14 per cent
increase) produces a reduction from 17.87 per cent to 12.78 per cent (a 28
per cent reduction) in the proportion of times than taxis are required. 
This seems worthwhile. 
    \item The actual reduction in the number of taxi journeys per hour is less than
28 per cent (it is 18.3 per cent) because the number of pods arriving per hour
has increased. 
\end{itemize}









%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage 
## Exercise 5
Comment on your results in part (iv).


(v)
Before a final decision is made to proceed the manager should consider the cost of
increasing the frequency of the pods and also consider customer feedback.



\end{document}
