---
title: "Statistics with R"
subtitle: "Statistical Modelling with R for Actuarial Students"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(knitr)
library(dplyr)
library(janitor)


```

```{css, echo=FALSE}
pre {
  background: #ADD8E6;
  max-width: 100%;
  overflow-x: scroll;
}
```

***CS2B – Risk Modelling and Survival Analysis ***


* The emphasis is placed on being able to apply statistical methods to actuarial problems using real data sets and the open-source software environment R. 

* Time Series. Probability Distributions, Survival Analysis

---
[20]
Q. 2) You have been asked to analyse the number of deaths per month in the country X from lung 
disease over the period from Jan 2015 to Dec 2020. This information is contained in a time 
series called “Lung_Deaths.csv”.
1.  Convert the data into a time series format representing the above period after loading it 
into R. (2)
2.  Plot this time series giving appropriate labels for each axis.
3.   Plot, on two separate graphs, the sample autocorrelation function (sample ACF) and 
sample partial autocorrelation function (sample PACF) of the series with appropriate 
labelling of the axes. (6)
IAI CS2B-0722
 Page 3 of 4
4.  Justify the presence of seasonality in the data based on (2.  and (3.   above.
5.  Apply seasonal differencing to the time series to remove the element of seasonality. (4)
6.   Plot the ACF and PACF of this time series generated in (5.  above up to lag k = 5 years, 
giving appropriate labels for each axis. (4)
7.  Comment on your plots in part (6.  , making reference to the stationarity.
